# Semua yang berhubungan dengan HTTP request
# Semua setting di file ini mengendalikan komunikasi HTTP

USER_AGENT = ...

DEFAULT_REQUEST_HEADERS = ...

COOKIES_ENABLED = True
COOKIES_DEBUG = False

COMPRESSION_ENABLED = True

DOWNLOAD_TIMEOUT = 30

CONCURRENT_REQUESTS = 16
CONCURRENT_REQUESTS_PER_DOMAIN = 1

DOWNLOAD_DELAY = 1
RANDOMIZE_DOWNLOAD_DELAY = True

RETRY_ENABLED = True
RETRY_TIMES = 3
RETRY_HTTP_CODES = [...]

REDIRECT_ENABLED = True
REDIRECT_MAX_TIMES = 20

AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 5
AUTOTHROTTLE_MAX_DELAY = 60
AUTOTHROTTLE_TARGET_CONCURRENCY = 1.0
AUTOTHROTTLE_DEBUG = False